#################################################################################
#  Copyright (c) 2025 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#  Copyright (c) 2025 SAP SE
#  Copyright (c) 2025 Fraunhofer Institute of Optronics, System Technologies
#  and Image Exploitation (Fraunhofer IOSB)
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0.
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#################################################################################

name: "Generate and validate DEPENDENCIES"
description: "Generate and checks DEPENDENCIES file."

inputs:
  run:
    description: How the dependencies check must be applied. The "standard" will fail only for 'rejected' dependencies, "strict" will fail also for 'restricted' ones.
    required: false
    default: standard

runs:
  using: "composite"
  steps:
    - name: Build project to correctly resolve dependencies
      shell: bash
      run: |
        mvn clean install -DskipTests

    - name: Generate dependency list
      shell: bash
      run: |
        mvn dependency:list > dependencies-unclean
        if grep -q "ERROR" dependencies-unclean; then exit 1;  fi
        cat dependencies-unclean | grep -o '[a-zA-Z0-9.-]\+:[a-zA-Z0-9.-]\+:jar:[0-9.]\+' | sed 's/:jar//' | sort | uniq > dependency-list
        sed -i '/de\.fraunhofer\.iosb\.ilt\.faaast\.service/d' dependency-list
        rm dependencies-unclean
        cat dependency-list

    - name: Print failure reason
      if: failure()
      shell: bash
      run: cat dependencies-unclean

    - name: Run dash
      id: run-dash
      uses: eclipse-tractusx/sig-infra/.github/actions/run-dash@main
      with:
        dash_input: dependency-list
        dependencies_file: DEPENDENCIES
        fail_on_out_of_date: false
        fail_on_rejected: true
        fail_on_restricted: ${{ inputs.run == 'strict' }}

    - name: Print file
      shell: bash
      if: failure()
      run: |
        echo "=== Please copy the following content back to DEPENDENCIES ==="
        cat DEPENDENCIES
        echo "=== end of content ==="
        exit 1
