name: "Generate and validate DEPENDENCIES"
description: "Generate and checks DEPENDENCIES file."

inputs:
  run:
    description: How the dependencies check must be applied. The "standard" will fail only for 'rejected' dependencies, "strict" will fail also for 'restricted' ones.
    required: false
    default: standard

runs:
  using: "composite"
  steps:
    - name: Generate dependency list
      shell: bash
      run: |
        mvn dependency:list > dependencies-unclean
        cat dependencies-unclean
        # Fail on ERROR -> (Some) dependencies could not be resolved
        if grep -q "ERROR" dependencies_unclean; then cat dependencies_unclean; exit 1;  fi
        cat dependencies-unclean | grep -o '[a-zA-Z0-9.-]\+:[a-zA-Z0-9.-]\+:jar:[0-9.]\+' | sed 's/:jar//' > dependency-list
        cat dependency-list

    - name: Run dash
      id: run-dash
      uses: eclipse-tractusx/sig-infra/.github/actions/run-dash@main
      with:
        dash_input: dependency-list
        dependencies_file: DEPENDENCIES
        fail_on_out_of_date: false
        fail_on_rejected: true
        fail_on_restricted: ${{ inputs.run == 'strict' }}

    - name: Print file
      shell: bash
      if: failure()
      run: |
        echo "=== Please copy the following content back to DEPENDENCIES ==="
        cat DEPENDENCIES
        echo "=== end of content ==="
        exit 1
